### ISSUE TITLE
Unable to add Neerslag App to Integration

### ISSUE THREAD

**Issue by arjenfvellinga** [aex351/home-assistant-neerslag-app#15]
I cleared the browser cache.

I added the repo url to the 'Manage add-on repositories' screen and it fails with the error: Invalid Add-on repository!

![image](https://user-images.githubusercontent.com/16539832/127319728-6c6cccb3-4b3e-4501-a536-ca4474a8fa92.png)

From the log:
```
21-07-28 14:04:01 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/aex351/home-assistant-neerslag-app repository
21-07-28 14:04:03 ERROR (MainThread) [supervisor.store] https://github.com/aex351/home-assistant-neerslag-app is not a valid add-on repository
21-07-28 14:04:03 INFO (MainThread) [supervisor.resolution.module] Create new issue IssueType.CORRUPT_REPOSITORY - ContextType.STORE / 7c2cdab7
21-07-28 14:04:03 INFO (MainThread) [supervisor.resolution.module] Create new suggestion SuggestionType.EXECUTE_REMOVE - ContextType.STORE / 7c2cdab7
21-07-28 14:04:03 WARNING (MainThread) [supervisor.store.data] No repository information exists at /data/addons/git/7c2cdab7
```

**Comment by aex351** [comment]
The Neerslag App is not an Home Assistant `add-on`. So the error you are seeing is correct. The Neerslag App is an Home Assistant `integration`. Both work differently and have different purposes. 

To easiest way to install the Neerslag App is through the Home Assistant Community Store (abbreviated and known as HACS). See https://hacs.xyz/ for more information. This is the default way for installing community integrations and front-end plugins.

**Comment by arjenfvellinga** [comment]
Aha, I did read that. And I was indeed confused about the directions. Maybe I can explain so someone later can learn from it.

"Add this repository to HACS;"

The first thing you see on the HACS tab is this:
![image](https://user-images.githubusercontent.com/16539832/127387629-ae8a3ec0-e30a-4981-a591-6bf5a4690211.png)

But I now see that's wrong, but not obvious.

Then there is this button on the integration page of HACS:
![image](https://user-images.githubusercontent.com/16539832/127387818-76c33401-3273-4cdd-8552-013d8bf85a52.png)
But there you can't add a new repository to HACS, only known ones.

So the correct location is 'Custom repositories' in the dot-menu
![image](https://user-images.githubusercontent.com/16539832/127387955-ecd3e98e-e087-46b7-ab39-a12e8ce02df9.png)

**Comment by aex351** [comment]
I have made a request to get the Neerslag App added to the default HACS repository, see: https://github.com/aex351/home-assistant-neerslag-app/issues/14. 

Closing this issue as there is nothing to add.
