### ISSUE TITLE
Card disappeared after update to core-2021.9.7

### ISSUE THREAD

**Issue by Calimerorulez** [aex351/home-assistant-neerslag-app#19]
Hi,

All was working OK, but after updating HA to core-2021.9.7, the card disappeared, and can't get it added again in lovelace.

It isn't even available in 'kaart toevoegen' (I don't know the English translation, because my UI is Dutch ;-) ).

**Comment by aex351** [comment]
Try clearing your cache and restart Home Assistant. I can't detect any issues with Home Assistant 2021.9.7. There are also no breaking changes introduced. Next to this make sure you are running the latest version of the Neerslag App

**Comment by Calimerorulez** [comment]
I removed and reinstalled the app, cleared cache, rebooted and now it works again, thank you for your advice :)
