### ISSUE TITLE
How to use sensor values for automations?

### ISSUE THREAD

**Issue by Mothamoz** [aex351/home-assistant-neerslag-app#20]
This is not so much an issue as it is a question. 
The sensor values are always between 0.0 - 0.99, they don't directly correspond to the values of rain in mm. 

How can I convert/use these values to get the actual rain data and use them for certain automations?

**Comment by aex351** [comment]
Currently those values, that are randomly generated, only give an indication that the sensors have been updated.

It still is on the backlog the change these to actual sensor data and/or add additional sensors that can be used for automations and other indications.

**Comment by Mothamoz** [comment]
Thank you for your reply, hopefully we'll see this in the future then!

**Comment by gvdhoven** [comment]
@aex351 if you already could add and expose a sensor which indicates that it is raining that would be cool. In addition (but optional) the mm/hr values from both sources could be exposed?

**Comment by gvdhoven** [comment]
p.s. by the looks of the code it would be relatively easy to do this. If i understand the code correctly, the `formatBuienradarData`, `formatBuienalarmData ` and `formatBuienalarmDataAndere` methods should be moved to the custom component (python script) so that all data is already prepared. Then, on every poll the sensors could be updated with the current precipitation values. I might take a crack at it and open a PR for this if you would be interested.

**Comment by aex351** [comment]
Thanks, I am reading two things and will provide some insight.

1. Feature request regarding additional sensors based on the available data from both the Buienradar and Buienalarm sensor;
2. Storing the data from both services in an uniform way. Currently the data is being fetched from Buienalarm and Buienradar and stored as-is. No data transformation is being applied.

It would definitively be nice to have all data stored in a uniform way. The reason why no data transformation has been applied is purely for simplicity. However, this is not a requirement for adding additional sensors. Any improvements or suggestions are of course welcome.

**Comment by JazekerXX** [comment]
> Currently those values, that are randomly generated, only give an indication that the sensors have been updated.
> 
> It still is on the backlog the change these to actual sensor data and/or add additional sensors that can be used for automations and other indications.

i was really confused with the random regen data sensors until i read this post.
maybe make a note in the readme file to mention this?

i was also wondering what the status is about making the sensor data usable for automations?
this would be awesome to automate my sunscreens etc.
just a notice of rain true/false or a number for mm/s within xx minutes would be ideal.
hopefully you can fix that?

in ieder geval bedankt ;)
thanks

**Comment by JeffreyvanNijnatten** [comment]
I've been struggling for a while with this data, until I understood the values have nothing to do with the rain-data.

**Comment by joshuisken** [comment]
Suggested a change request to resolve this. See pull request #52.
