### ISSUE TITLE
Error: incompatible integration detected

### ISSUE THREAD

**Issue by robbinonline** [aex351/home-assistant-neerslag-app#23]
I got the error: incompatible integration detected
1. buien-rain-forecast
 This integration is known for causing problems with the Neerslag Card. Please remove it. 

I have no other weather plugins/ integrations installed, also no entity with that name.
How to solve?

**Comment by robbinonline** [comment]
<img width="503" alt="Schermafbeelding 2022-01-05 om 15 50 55" src="https://user-images.githubusercontent.com/660835/148237753-c4fc94d9-08ee-4375-a40f-5d171f9970b1.png">

**Comment by aex351** [comment]
You will need to remove that other integration / plug-in. You most likely installed it in the past and the files are still present. Your Home Assistant is still loading it.
