### ISSUE TITLE
Not showing

### ISSUE THREAD

**Issue by JanStalenburg** [aex351/home-assistant-neerslag-app#25]
Hi,

I installed the app via HACS and configure it via settings and integration.
I won't see the card if I added it via the configuring UI tab.

I see via developers tools that it will pick-up data from buienalarm and buienradar.

So something is wrong but have no idea what.

**Comment by aex351** [comment]
If you follow the installation instructions - without skipping a step - everything should work. This also includes restarting Home Assistant at various steps and/or possible clearing the browser cache. Please read and follow the installation instruction carefully.

**Comment by JanStalenburg** [comment]
Found the problem at my side. I had the configuration in two config files.
I just removed one but the other was still defined in anther file.
I removed the entries and after that I deleted the integration and added again.
After giving the locations I saw that it was working fine.
Sorry I disturbed you with this useless issue.
