### ISSUE TITLE
Wrong Reading

### ISSUE THREAD

**Issue by miit86** [aex351/home-assistant-neerslag-app#30]
Hi,

I use this sensors to automatically close my sunscreen when it rains. 
when sensor is above 0.25 it closes.
I have a lot of false positives lately. also tried 0.75 as value for closing.

as i'm typing the state of the sensor.neerslag_buienalarm_regen_data = 0.814938603267205
all the forecasts are 0
outside there isn't even a cloud in the sky.
also the buienalarm.nl website say 0 mm.

so whats going on with the 0.81 reading?

Kind Regards,

**Comment by aex351** [comment]
The sensor state currently is a random number and changed on each sensor update. It is an easy debug mechanism that allows you to check if the sensor is working. If the number doesn't update, there is an issue with the sensor.

In an upcoming update new features will be added so you can use this integration in your automations.

**Comment by joshuisken** [comment]
Suggested a change request to resolve this. See pull request [#52](https://github.com/aex351/home-assistant-neerslag-app/pull/52).
