### ISSUE TITLE
Failed to execute 'define' on 'CustomElementRegistry': the name "neerslag-card" has already been used with this registry

### ISSUE THREAD

**Issue by haaino** [aex351/home-assistant-neerslag-app#36]
Logger: frontend.js.latest.202208020
Source: components/system_log/__init__.py:227
First occurred: 14 August 2022 at 15:20:39 (32 occurrences)
Last logged: 16:14:13

https://.ui.nabu.casa/frontend_latest/app.933bd729.js:850:203613 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "neerslag-card" has already been used with this registry
https://ui.nabu.casa/lovelace-lampen/0:0:0 Uncaught
:0:0 Script error.
https://.ui.nabu.casa/frontend_latest/95446709.js:1:351 Uncaught RangeError: Value need to be finite number for Intl.RelativeTimeFormat.prototype.format()
https://5ui.nabu.casa/lovelace/0:0:0 Uncaught

**Comment by aex351** [comment]
The error message seems that the `neerslag card` gets loaded twice for some reason on your end. From a default install I have not seen this error message. I will leave this issue/thread open for some time for potential replies. If not, I will close this thread.

**Comment by haaino** [comment]
Thanks

Sorry for my novice question, but where in the configuration files I can check this? Perhaps I can comment one load action?

Perhaps it is not simple as I think 😊

**Comment by kranendijk** [comment]
Having the same issue for a while, did not feel the urge to post it. Now I do 😁 Not aware of double installations or entries though…
It is used on multiple dashboards, could that be an issue?

Logger: frontend.js.latest.202211021
Source: components/system_log/__init__.py:256 
First occurred: 07:07:39 (3 occurrences) 
Last logged: 18:45:51

https://sxir70kg89bavculw8ihb449xjfhjkyk.ui.nabu.casa/frontend_latest/app.92b32e63.js:850:203613 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "neerslag-card" has already been used with this registry
http://192.168.2.50:8123/frontend_latest/app.92b32e63.js:850:203613 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "neerslag-card" has already been used with this registry

**Comment by MV812** [comment]
had this same issue, removing the home-assistant-neerslag-card directory from  /custom_components/neerslag solved it for me.

**Comment by nov1n** [comment]
I have the same error message in my logs. I tried removing and adding the integration again, but the issue persisted. Strangely enough, I even see this error after I removed the card from all my dashboards. Any way I can help debug this?
