### ISSUE TITLE
No sensor data available (while the is data in the sensor)

### ISSUE THREAD

**Issue by MrPePperNL** [aex351/home-assistant-neerslag-app#39]
Hello,

First of all thanks for the wonderfull work you did on this app and card.

However as the title states I seem to have a weird problem with the card display. It shows very often the message : **no sensor data available**. My guess it's 90% of time this message and only 10% of time a nice graph.

When looking at the sensor data in entities it shows a value for both buienalarm as well as buienradar.

I tried clear browser cache, other browser , another pc which had never connected to my home-assistant. Reinstalled the app on my phone. Installed app on my android tablet, all experience the same.

Can you help me get it working correctly again ?

**Comment by aex351** [comment]
No sensor data available can happen when the external service used to fetch the rain can't be reached. This can be because the external service is not working or there is a connectivity issues with your internet connection. This with the fact that you describe there are moments it is working for you. 

This means it is not an issue with the `neerslag-app`.  Also make sure to use the `neerslag-app` and not the standalone `neerslag-card`.

**Comment by MrPePperNL** [comment]
Hello aex351,

Thanks for your response. I checked and I only have the neerslag-app installed.

If there is a problem with fetching the data , how can I troubleshoot it ?

I think it's not that the data is not fetched , as I can see the sensors filled with data over time (in history and in the sensors themself), I alsocreated a graph card on my dashboard which is filled with data.

Might it have something to do with my settings , My language is set to English and number format set to 1 234 567,89, values in the sensor are like 0.0770470814585514.

Any other suggestions ?

**Comment by RefleCs** [comment]
How can we test this? I have the same issue.

**Comment by MrPePperNL** [comment]
Seems I still have this issue, tried with several browsers on several computers.

What logs are needed to investigate the issue ?

**Comment by aex351** [comment]
Did the card work for you correctly before?

You can have a look at the browser console, to see if any error messages show up.

**Comment by MrPePperNL** [comment]
I don't really knoww if it ever worked correctly, had it on another tab of the dashboard but it's now on the main dashboard so hence I see it more often.

I'm mostly using the app on my android phone to display the dashboard. Will have a look using a browser and the console to check for errors.

**Comment by deirisu** [comment]
Hello, 
I have a same issue and it went a little further where the graph shows up but with no data on it.
![image](https://user-images.githubusercontent.com/119290662/210206113-5cd8f7dd-49bd-4181-a164-ede8e9783bf3.png)
 
If i add the second sensor, it crashes and nothing show up

**Comment by aex351** [comment]
@deirisu, you will need to set-up the sensors. See the readme file. Also do note that not every country is supported.

**Comment by wernerkarlheisenberg** [comment]
I believe I'm facing a similar issue. I live in Belgium.

When I try to add the neerslag-card I get 'No sensor data available'.
![image](https://user-images.githubusercontent.com/20357407/215865810-2b05a43a-bea3-48a3-8eff-6235ddf45e87.png)

When I look at sensor values, clearly they contain data ...
![image](https://user-images.githubusercontent.com/20357407/215866154-0a563493-47e8-47a4-8f83-20fa7ab41829.png)

**Comment by mirkin-pixel** [comment]
I have the same issue as @wernerkarlheisenberg and @deirisu

**Comment by thoompje** [comment]
Same issue here, any updates?

**Comment by aex351** [comment]
The sensor needs to contain usable rain data. Have a look at the sensor in the developer tool section.

**Comment by thoompje** [comment]
> The sensor needs to contain usable rain data. Have a look at the sensor in the developer tool section.
> 
> 
> 
> 

Hi, thanks for the quick response! Here is the sensor![image](https://github.com/aex351/home-assistant-neerslag-app/assets/37865789/d19163e2-a30c-415c-9b88-1502ee6cd06b)

**Comment by aex351** [comment]
Your sensor is `neerslag_buienradar_regen_data` and you're trying to display `neerslag_buienalarm_regen_data`.

**Comment by thoompje** [comment]
> Your sensor is `neerslag_buienradar_regen_data` and you're trying to display `neerslag_buienalarm_regen_data`.

I see it, this is so stupid haha. Sorry! Thanks for helping
