### ISSUE TITLE
How are buienradar values converted to mm/hr

### ISSUE THREAD

**Issue by TheFes** [aex351/home-assistant-neerslag-app#43]
I want to plot a graph myself using the values in the buienradar sensor (as it seems to be more accurate than the buienalarm sensor).
However, the values in the buienradar sensor are e.g. `102, 106, 099` (with a timestamp inlcuded as well) and the values in the graph are `0.6, 0.81, 0.49` If I divide these with each other, Can you tell me how I can calculate the values in the sensor to the mm/hr values?

**Comment by aex351** [comment]
Buienradar has a public api. Their page describes the math to convert the data to useable information: https://www.buienradar.nl/overbuienradar/gratis-weerdata
