### ISSUE TITLE
Card not available

### ISSUE THREAD

**Issue by 2-MAdD** [aex351/home-assistant-neerslag-app#47]
i've installed this according to 1a. Install via HACS (recommended).
Rebooted the HA.
After the reboot i've followed this: Configure the Neerslag App (via interface)
But now when i want to create a new dashboard, i'm getting this error:
Custom element not found: neerslag-card

what can be wrond.
![neerslag1](https://github.com/aex351/home-assistant-neerslag-app/assets/54440018/6e831eb8-7db6-4d10-88c6-fc1b1227a9c6)
![neerslag2](https://github.com/aex351/home-assistant-neerslag-app/assets/54440018/dd8506d4-a9b8-4cde-9d63-d4b6e33e52f5)
![neerslag3](https://github.com/aex351/home-assistant-neerslag-app/assets/54440018/f7507f47-da2a-4f26-b34e-0638416ed22b)
![neerslag4](https://github.com/aex351/home-assistant-neerslag-app/assets/54440018/5a03d8ab-771b-4f74-832d-347a5af13026)
![neerslag5](https://github.com/aex351/home-assistant-neerslag-app/assets/54440018/3a118500-2ea1-423b-86ad-282b29a84c9d)

What could be wrong?

**Comment by aex351** [comment]
Could be a caching problem with your browser. Try clearing the cache and/or as test use a private/incognito window.

**Comment by 2-MAdD** [comment]
@aex351 it isnt a cache issue, as i see this on different devices (win11 machine, ipad, iphone)
tried that before on above devices, but all give the same error (also with the app)

**Comment by aex351** [comment]
The error basically means the Neerslag Card (the frontend part) is not loading. Can you check your browser console window and Home Assistant logs?

**Comment by realjax** [comment]
Same problem here

**Comment by poksh** [comment]
same problem

**Comment by Soulfly999** [comment]
> same problem, and I don't see Neerslag Card in the 'Add Card' list
> 
> upd, records from chrome's console (my domain replaced by MYDOMAIN):
> 
>     * general:1 Access to script at 'https://unpkg.com/@lit/reactive-element@%5E1.3.0?module' from origin 'https://MYDOMAIN' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> 
>     * lit-element.js:1 GET https://unpkg.com/@lit/reactive-element@%5E1.3.0?module net::ERR_FAILED 520
> 
>     * general:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://MYDOMAIN/neerslag-card.js?cache=1712906259.0936947

Same problem, looks like [https://unpkg.com/@lit](https://unpkg.com/@lit/reactive-element@%5E1.3.0?module) is not availabel

**Comment by aex351** [comment]
Will look in to this. Seems that currently there is an issue with unpkg, for which there is a dependency. Going forward, there has been a plan to remove this dependency. On short term, let's see if the connectivity issue resolves itself within some hours, if not will look for a quick fix.

**Comment by aex351** [comment]
Issue has resolved itself.

**Comment by poksh** [comment]
and it broke again

**Comment by Soulfly999** [comment]
I didn't checked it yesterday, but today it works again. 

![2024-04-13 12_32_20-Übersicht – Home Assistant – Mozilla Firefox](https://github.com/aex351/home-assistant-neerslag-app/assets/4936794/92e1a415-f2d4-46f7-89ec-f0b2432e976d)

**Comment by aex351** [comment]
@poksh, this issue has been completely mitigated. See: #40. Try updating the `neerslag-app` to the latest version and clear your local cache.
