### ISSUE TITLE
Suddenly no sensor data available 

### ISSUE THREAD

**Issue by thoompje** [aex351/home-assistant-neerslag-app#48]
The sensor data is not available on the card.

Here are the screenshots with all the information you need (I think).

<img width="568" alt="Screenshot 2023-11-26 at 17 43 57" src="https://github.com/aex351/home-assistant-neerslag-app/assets/37865789/1708c458-792e-4f21-934a-2ad2eeb0be1c">
<img width="461" alt="Screenshot 2023-11-26 at 17 43 49" src="https://github.com/aex351/home-assistant-neerslag-app/assets/37865789/9c180525-bbbc-455d-b726-83e0688625ee">
<img width="470" alt="Screenshot 2023-11-26 at 17 43 44" src="https://github.com/aex351/home-assistant-neerslag-app/assets/37865789/31e320e0-5c94-413f-bbaf-b114b6399def">

Core
2023.11.3
Supervisor
2023.11.3
Operating System
Frontend
20231030.2

**Comment by Klapperman** [comment]
Yes, I've been reading out the data in a Node-red function and the data from Buienradar has been empty now for about 3 days sometimes it shortly pops up but then disappears again. Buienalarm does work.

**Comment by haaino** [comment]
It seems that the supplier has fixed the issue. It started working on my end again.

**Comment by aex351** [comment]
The Buienradar api is working again. No change has been made for the `neerslag-app`.
