### ISSUE TITLE
Set thresholds for low/medium/high rain

### ISSUE THREAD

**Issue by sylvainvrolijk** [aex351/home-assistant-neerslag-app#49]
Hi aex351,

Currently the standard graph has a Y axis to 6 mm/hr. Most rain is showing as light, even though it rains quite a bit (< 1mm/hr). This makes the graph a bit hard to read. Is it possible to change the Y axis parameters, to show up to a smaller amount? Or dynamically?

Thanks!

**Comment by aex351** [comment]
There is an option `autozoom`, which you can set to `true` or `false`. See also the readme. You can configure this trough the card.

`autozoom: true` starts with the graph zoomed in. The graph will zoom out based on the current/actual rainfall.
`autozoom:false` starts with the graph zoomed out. If needed the graph will zoom out more based on the current/actual rainfall.
