### ISSUE TITLE
Neerslag App not appearing as Integration

### ISSUE THREAD

**Issue by Sundown89** [aex351/home-assistant-neerslag-app#5]
I just installed this Neerslag App in Home Assistant through HACS but after a restart nothing appears in config/integrations. How do I "add the Neerslag App as an Integration"? I can't complete step 2. Configure the Neerslag App (via interface). Is there any way I can complete the configuration manually?

I'm on Home Assistant Core, running on Ubuntu 18.04.

**Comment by aex351** [comment]
There is no way that I am aware of to complete the installation manually. 

Home Assistant should list the Neerslag App that has been downloaded via HACS. You can try to download the Neerslag App manually and place it in to the correct folder, `/custom_components/`. You will still need to 'install' the integration via the Home Assistant add integration button.

**Comment by Sundown89** [comment]
Under 'add integration' the app was not listed, eventhough every step until then was correctly taken. 
After I cleared my browser's cache it was correctly listed under 'add integrations' after which I could install the integration. 
Putting it here for future reference if this occurs to more users. 

Can be closed.
