### ISSUE TITLE
Timeout on Buienradar

### ISSUE THREAD

**Issue by haaino** [aex351/home-assistant-neerslag-app#50]
Hi,

Since a few days I'm seeing a "timeout" issue. I see the following in the logfile: "2024-04-30 13:22:28.719 INFO (MainThread) [custom_components.neerslag.sensor] getBuienradarData - timeout".

Anyone else have the same issue?

Best regards,
Haaino

**Comment by Failure404** [comment]
Unfortunately, the only thing I can say is

Same here.

**Comment by rvdv01** [comment]
Indeed, since a few days it shows ‘geen sensordata beschikbaar’ instead of a graph on the card.

**Comment by aex351** [comment]
The Buienradar API output seems to have been slightly modified. I have implemented a fix so that the `neerslag-app` is able to process the data again.

**Comment by haaino** [comment]
Works for me ☺️ thank you
