### ISSUE TITLE
Lat/Lng wrong? How to edit lat/lng of App

### ISSUE THREAD

**Issue by CreaticDD** [aex351/home-assistant-neerslag-app#51]
How can I modify the latitude and longitude used by the Neerslag App?

I suspect it's wrong.

**Comment by aex351** [comment]
You can configure it. See the readme file on how to do that.

**Comment by CreaticDD** [comment]
Well no. I tried that but it shows a blank popup as follows:
![Screenshot 2024-05-14 164254](https://github.com/aex351/home-assistant-neerslag-app/assets/47812491/d5d9c7d8-06ed-4808-ae2c-54bf40f50324)

**Comment by aex351** [comment]
Could you share the settings you use? Next to that, is there any information in the console or log files?
