### ISSUE TITLE
works in browser (windows/firefoxe), not in app (ios)

### ISSUE THREAD

**Issue by jaspov** [aex351/home-assistant-neerslag-app#61]
Got it working on my laptop. 
However when I open the HA app in iOS it shows:

Custom element doesn't exist: neerslag-card
type: custom:neerslag-card
entity:
sensor.neerslag_buienalarm_regen_data
title: Neerslag

Did I add it wrong or is it supposed to only work on laptops?

**Comment by aex351** [comment]
It should also work on the mobile app. I think this issue is related to #59. Try updating to the latest Home Assistant version available. The card should then start to work again. It might require to clear the app cache first.
